// Static crew + plans data scraped from the original Wix site
// (Crew CMS collection not available via API; Plans API unavailable)

const BASE = 'https://static.wixstatic.com/media';

export const STATIC_CREW = [
  {
    slug: 'captain-whiskers',
    title: 'Captain Whiskers',
    role: 'Captain',
    status: 'Active',
    bio: 'A battle-scarred tabby with 9 lives and counting. Led the Great Migration from the Kitchen Counter to the Top of the Fridge. Now commands the flagship vessel SS Scratching Post. Known for making impossible decisions look effortless, usually while grooming.',
    specialSkill: 'Strategic Napping',
    funFact: 'Has knocked over 2,847 objects across 3 star systems',
    image: `${BASE}/4975b6_941598c83a6445529c7250fc9f6a3cab~mv2.png/v1/fill/w_400,h_400,al_c,q_85,enc_auto/captain-whiskers.png`,
  },
  {
    slug: 'dr-mittens',
    title: 'Dr. Mittens',
    role: 'Chief Scientist',
    status: 'Active',
    bio: 'A Siamese genius who earned her doctorate in Astro-Purr-ysics from the University of the Windowsill. Developed the theory of Feline Relativity: time moves slower when you\'re waiting for food. Currently researching which planets have the best sunbeam angles.',
    specialSkill: 'Quantum Box Theory',
    funFact: 'Can calculate orbital trajectories while simultaneously ignoring you',
    image: `${BASE}/4975b6_be1e4c7c179b4efb9fbbfd705b5b0e02~mv2.png/v1/fill/w_400,h_400,al_c,q_85,enc_auto/dr-mittens.png`,
  },
  {
    slug: 'major-floof',
    title: 'Major Floof',
    role: 'Pilot',
    status: 'On Mission',
    bio: 'A magnificent Persian whose fur defies the laws of physics. The best pilot in the fleet, capable of navigating asteroid fields while half asleep (which is most of the time). Her landing technique is described as \'always on her feet.\'',
    specialSkill: 'Zero-G Hairball Navigation',
    funFact: 'Her fur has its own gravitational field',
    image: `${BASE}/4975b6_034c3c8970ec43388a6c63ddc64c0de0~mv2.png/v1/fill/w_400,h_400,al_c,q_85,enc_auto/major-floof.png`,
  },
  {
    slug: 'sergeant-beans',
    title: 'Sergeant Beans',
    role: 'Engineer',
    status: 'Active',
    bio: 'A tuxedo cat who can fix anything with enough determination and headbutts. Built the ship\'s engine from a cardboard box, three rubber bands, and pure spite. If it fits, he sits — and if it doesn\'t fit, he\'ll make it fit.',
    specialSkill: 'If It Fits, It Ships',
    funFact: 'Once rewired the entire navigation system while chasing a laser pointer',
    image: `${BASE}/4975b6_c881199ebb234534b7f9bbc1e60815e4~mv2.png/v1/fill/w_400,h_400,al_c,q_85,enc_auto/sergeant-beans.png`,
  },
  {
    slug: 'lieutenant-biscuits',
    title: 'Lieutenant Biscuits',
    role: 'Communications Officer',
    status: 'Active',
    bio: 'An orange tabby with exactly one brain cell, which is entirely dedicated to making biscuits (kneading). Despite this, she\'s somehow the most effective communicator on the crew. Her purring frequency can be picked up across 12 parsecs.',
    specialSkill: 'Hypersonic Purring',
    funFact: 'Has never once thought about the consequences of anything',
    image: `${BASE}/4975b6_dcf65ac2346b45af904f5303cea365ba~mv2.png/v1/fill/w_400,h_400,al_c,q_85,enc_auto/lieutenant-biscuits.png`,
  },
  {
    slug: 'commander-void',
    title: 'Commander Void',
    role: 'Stealth Operations',
    status: 'Active',
    bio: 'A solid black cat who appears and disappears at will. Nobody knows how she gets into locked rooms or sealed cargo bays. Runs all covert operations and 3 AM zoomie drills. If you can\'t see her, she can definitely see you.',
    specialSkill: 'Quantum Invisibility',
    funFact: 'Has been found in 14 impossible locations this week alone',
    image: `${BASE}/4975b6_fd7dcd158fde4185b2e16c90b81e52ee~mv2.png/v1/fill/w_400,h_400,al_c,q_85,enc_auto/commander-void.png`,
  },
];

export const STATIC_PLANS = [
  {
    id: 'space-cadet',
    name: 'Space Cadet',
    description: 'Enhanced features for the aspiring space explorer',
    priceDisplay: '₪9.99',
    period: 'month',
    isFree: false,
    highlighted: false,
    freeTrialDays: 7,
    perks: [
      'Everything in Free Explorer',
      'Access to premium blog content',
      'Priority comment placement',
      'Exclusive crew badge',
      '7-day free trial',
    ],
  },
  {
    id: 'captains-circle',
    name: "Captain's Circle",
    description: 'The ultimate membership for true space commanders',
    priceDisplay: '₪24.99',
    period: 'month',
    isFree: false,
    highlighted: true,
    freeTrialDays: 14,
    perks: [
      'Everything in Space Cadet',
      'Write your own blog posts',
      "Captain's badge & custom title",
      'Direct access to Mission Control',
      'Vote on next planet destinations',
      '14-day free trial',
    ],
  },
  {
    id: 'free-explorer',
    name: 'Free Explorer',
    description: 'Start your space journey with basic access',
    priceDisplay: 'Free',
    period: null,
    isFree: true,
    highlighted: false,
    freeTrialDays: 0,
    perks: [
      'Access to all planet data',
      "Read the Ship's Log",
      'Comment on blog posts',
      'Basic crew profile',
    ],
  },
];